In [1]:
# 1. Import the numpy package under the name np 


import numpy as np

In [2]:
#2. Print the numpy version and the configuration (★☆☆)

print(np.__version__)
np.show_config()

1.24.4
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

In [4]:
#3. Create a null vector of size 10 (★☆☆)
null = np.zeros(10)
print(null)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
# 4. How to find the memory size of any array (★☆☆)

memory_size = np.zeros((10,10))
print("%d bytes" % (memory_size.size * memory_size.itemsize))

800 bytes


In [30]:
#5. How to get the documentation of the numpy add function from the command line?
import numpy as np
np.info(np)

NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly t

In [7]:
#6. Create a null vector of size 10 but the fifth value which is 1

null_value = np.zeros(10)
null_value[4] = 1
print(null_value)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [8]:
#7. Create a vector with values ranging from 10 to 49

vector = np.arange(10,50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [12]:
# 8. Reverse a vector (first element becomes last

reversed_vector = np.arange(50)
reversed_vector = reversed_vector[::-1]
print(reversed_vector)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


In [13]:
#9. Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
# 10. Find indices of non-zero elements from [1,2,0,0,4,0]
nz = np.nonzero([1, 2, 0, 0, 4, 0])
print(nz)

(array([0, 1, 4]),)


In [10]:
#11. Create a 3x3 identity matrix

three_by_three = np.eye(3)
print(three_by_three)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# 12. Create a 3x3x3 array with random values

random_values = np.random.random((3,3,3))
print(random_values)

[[[0.25626557 0.06585594 0.21036772]
  [0.74287965 0.08271955 0.24688241]
  [0.67601744 0.08794973 0.70156907]]

 [[0.26640155 0.11983178 0.76024157]
  [0.45572186 0.21702823 0.02258655]
  [0.68941707 0.15934953 0.20465621]]

 [[0.7398652  0.51215418 0.62034848]
  [0.24040863 0.89894713 0.03315591]
  [0.87022932 0.95435763 0.15380553]]]


In [12]:
#13. Create a 10x10 array with random values and find the minimum and maximum values
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)

0.00444303542876634 0.9987054201477619


In [13]:
# 14. Create a random vector of size 30 and find the mean value
v = np.random.random(30)
m = v.mean()
print(m)

0.5205277515305621


In [14]:
#15 Create a 2d array with 1 on the border and 0 inside
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [15]:
#16. How to add a border (filled with 0's) around an existing array

Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [16]:
#17. What is the result of the following expression?
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


In [17]:
#18.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
matrix = np.diag(1+np.arange(4),k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [18]:
#19  Create a 8x8 matrix and fill it with a checkerboard pattern

Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [19]:
#20 Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [20]:
#21  Create a checkerboard 8x8 matrix using the tile function
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [21]:
#22. Normalize a 5x5 random matrix

Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)

[[-1.70586017  0.97406206 -1.39178725  0.15789099 -0.94229725]
 [ 0.27100816  1.36864345 -0.06453985 -0.8117575   1.71043621]
 [ 0.18852425 -1.23538158 -0.43070675  0.2766592  -0.82514356]
 [ 1.04436904  1.95139375  1.09362219 -0.34581771 -1.42552142]
 [ 0.13882014 -0.31444738 -0.49396497  1.21625297 -0.404457  ]]


In [22]:
#23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

In [23]:
# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [24]:
# 25. Given a 1D array, negate all elements which are between 3 and 8, in place.
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [25]:
# 26. What is the output of the following script?
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [15]:
# 27. Consider an integer vector Z, which of these expressions are legal?
Z = 5
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z



False

In [31]:
# 28. What are the result of the following expressions?

np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

/tmp/ipykernel_904/2852469938.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)
/tmp/ipykernel_904/2852469938.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)
/tmp/ipykernel_904/2852469938.py:3: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([-9.22337204e+18])

In [32]:
# 29. How to round away from zero a float array ?

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

[-5.  4. -2. -8. -8. -9.  7.  3. -9.  3.]


In [33]:
# 30. How to find common values between two arrays?

Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[5 6 8]


In [34]:
# 31. How to ignore all numpy warnings (not recommended)?
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

In [35]:
# 32. Is the following expressions true? (★☆☆)

np.sqrt(-1) == np.emath.sqrt(-1)

False

In [41]:
# 33. How to get the dates of yesterday, today and tomorrow? 

yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)

# Convert to standard datetime objects
yesterday = yesterday.astype('datetime64[D]').tolist()
today = today.astype('datetime64[D]').tolist()
tomorrow = tomorrow.astype('datetime64[D]').tolist()

print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)


Yesterday: 2024-02-20
Today: 2024-02-21
Tomorrow: 2024-02-22


In [42]:
# 34. How to get all the dates corresponding to the month of July 2016?


Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [43]:
# 35. How to compute ((A+B)*(-A/2)) in place (without copy)?

A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

In [44]:
# 36. Extract the integer part of a random array of positive numbers using 4 different methods

Z = np.random.uniform(0,10,10)

print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[9. 1. 8. 2. 3. 3. 6. 3. 4. 9.]
[9. 1. 8. 2. 3. 3. 6. 3. 4. 9.]
[9. 1. 8. 2. 3. 3. 6. 3. 4. 9.]
[9 1 8 2 3 3 6 3 4 9]
[9. 1. 8. 2. 3. 3. 6. 3. 4. 9.]


In [45]:
# 37. Create a 5x5 matrix with row values ranging from 0 to 4 

Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [46]:
# 38. Consider a generator function that generates 10 integers and use it to build an array 


def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [47]:
# 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded 


Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [48]:
# 40. Create a random vector of size 10 and sort it 


Z = np.random.random(10)
Z.sort()
print(Z)

[0.03911062 0.04321271 0.12550415 0.14728863 0.5510285  0.73271178
 0.7916073  0.81817834 0.83506101 0.88678965]


In [49]:
# 41. How to sum a small array faster than np.sum? 


Z = np.arange(10)
np.add.reduce(Z)

45

In [52]:
# 42. Consider two random array A and B, check if they are equal (★★☆)


A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)


False


In [20]:
# 43. Make an array immutable (read-only) (★★☆)

import numpy as np

Z = np.zeros(10)
Z.flags.writeable = False

In [54]:
# 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)


Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.23602231 0.6045452  0.48630568 0.36139735 0.77020121 0.65932586
 0.73773641 0.88800798 0.4931674  0.85147253]
[0.80093195 1.18743852 1.32585737 0.20948017 0.19563326 0.77709247
 1.23699524 1.42922134 0.20289365 1.13421444]


In [55]:
#45. Create random vector of size 10 and replace the maximum value by 0

Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.3925755  0.50440045 0.         0.250962   0.12389989 0.71550337
 0.29932148 0.70936229 0.84249479 0.68130408]


In [56]:
# 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)


Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


In [57]:
# 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)



X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))

3638.163637117973


In [58]:
# 48. Print the minimum and maximum representable value for each numpy scalar type 


for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


In [59]:
# 49. How to print all the values of an array? 


np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [61]:
# 50. How to find the closest value (to a given scalar) in a vector? (★★☆)


Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index]

SyntaxError: unexpected EOF while parsing (2511997139.py, line 7)

In [62]:
# 51. Create a structured array representing a position (x,y) and a color (r,g,b) 


Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/tmp/ipykernel_904/3591932922.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  Z = np.zeros(10, [ ('position', [ ('x', float, 1),


In [63]:
# 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)


Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.62054303 0.43452072 0.58420949 0.32758685 0.83911
  0.53863874 0.24484047 0.18980392 0.6833874 ]
 [0.62054303 0.         0.44564681 0.22068043 0.90943368 0.27449892
  0.66041391 0.54450243 0.7683113  0.51940564]
 [0.43452072 0.44564681 0.         0.57404427 0.75847323 0.52836676
  0.220267   0.5564878  0.62425836 0.82593468]
 [0.58420949 0.22068043 0.57404427 0.         0.81599225 0.48270311
  0.79375924 0.42639036 0.68655065 0.29918026]
 [0.32758685 0.90943368 0.75847323 0.81599225 0.         1.15037122
  0.82972531 0.39033035 0.14382965 0.80160054]
 [0.83911    0.27449892 0.52836676 0.48270311 1.15037122 0.
  0.69753243 0.80651278 1.00674484 0.77148616]
 [0.53863874 0.66041391 0.220267   0.79375924 0.82972531 0.69753243
  0.         0.72031677 0.71521395 1.03743141]
 [0.24484047 0.54450243 0.5564878  0.42639036 0.39033035 0.80651278
  0.72031677 0.         0.26868971 0.44988869]
 [0.18980392 0.7683113  0.62425836 0.68655065 0.14382965 1.00674484
  0.71521395 0.26868971

In [64]:
# 53. How to convert a float (32 bits) array into an integer (32 bits) in place?



Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[36 75 24 59 40 26 24 23 40 44]


In [ ]:
from io import StringIO
import numpy as np

# Fake file
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')

# Specify dtype as float since some entries are empty
Z = np.genfromtxt(s, delimiter=",", dtype=np.float, filling_values=np.nan)
print(Z)

In [32]:
# 55. What is the equivalent of enumerate for numpy arrays? 


Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [36]:
56. #Generate a generic 2D Gaussian-like array

X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

In [38]:
#57. How to randomly place p elements in a 2D array? 

import numpy as np

# Size of the 2D array
rows, cols = 4, 5
array_size = rows * cols

p = 8

# Create a 2D array filled with zeros
array_2d = np.zeros((rows, cols), dtype=int)

# Generate random indices to place elements
indices_to_place = np.random.choice(array_size, p, replace=False)

# Assign random values to the selected indices
array_2d.flat[indices_to_place] = np.random.randint(1, 10, p)

print(array_2d)


[[5 5 8 0 0]
 [0 6 1 0 0]
 [0 1 0 0 2]
 [0 0 0 2 0]]


In [40]:
# 58. Subtract the mean of each row of a matrix


import numpy as np

# Create a sample matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Subtract the mean of each row
result_matrix = matrix - np.mean(matrix, axis=1, keepdims=True)

print(result_matrix)


[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


In [41]:
# 59. How to sort an array by the nth column?


Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[9 0 7]
 [1 8 3]
 [7 2 0]]
[[9 0 7]
 [7 2 0]
 [1 8 3]]


In [42]:

## 60. How to tell if a given 2D array has null columns?
import numpy as np

def has_null_columns(array):
    return np.any(np.all(array == 0, axis=0))


array1 = np.array([[1, 0, 3],
                   [0, 0, 0],
                   [4, 0, 6]])

array2 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Array 1 has null columns:", has_null_columns(array1))
print("Array 2 has null columns:", has_null_columns(array2))


Array 1 has null columns: True
Array 2 has null columns: False


In [44]:
# 61. Find the nearest value from a given value in an array

import numpy as np

def find_nearest_value(array, value):
    array = np.asarray(array)
    idx = (np.abs(array - value)).argmin()
    return array[idx]

#example
my_array = np.array([1, 3, 5, 7, 9, 11])

given_value = 6
nearest_value = find_nearest_value(my_array, given_value)

print(f"Array: {my_array}")
print(f"Given Value: {given_value}")
print(f"Nearest Value: {nearest_value}")


Array: [ 1  3  5  7  9 11]
Given Value: 6
Nearest Value: 5


In [45]:
## 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator?


A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [46]:
# 63. Create an array class that has a name attribute 



class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


In [47]:
# 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)



Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

np.add.at(Z, I, 1)
print(Z)

[4. 4. 4. 2. 3. 3. 3. 2. 2. 3.]
[7. 7. 7. 3. 5. 5. 5. 3. 3. 5.]


In [48]:
# 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)?


X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


In [49]:
## 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors


w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


In [51]:
# 67. Considering a four dimensions array, how to get sum over the last two axis at once? 

A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[57 45 51 36]
 [57 52 54 58]
 [58 52 55 44]]
[[57 45 51 36]
 [57 52 54 58]
 [58 52 55 44]]


In [52]:
 #68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices?
import numpy as np

def subset_means(D, S):
    unique_indices = np.unique(S)
    bin_counts = np.bincount(S, weights=D)
    means = bin_counts[unique_indices] / np.bincount(S)

    return means

# Example 
D = np.array([1, 2, 3, 4, 5, 6])
S = np.array([0, 1, 0, 1, 2, 2])

result = subset_means(D, S)
print("Vector D:", D)
print("Subset Indices S:", S)
print("Subset Means:", result)


Vector D: [1 2 3 4 5 6]
Subset Indices S: [0 1 0 1 2 2]
Subset Means: [2.  3.  5.5]


In [53]:
# 69. How to get the diagonal of a dot product?

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

np.sum(A * B.T, axis=1)

array([1.66580971, 1.76960284, 1.35146226, 0.50486009, 0.8483277 ])

In [54]:
#70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value?

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]
